name: multigpu-rivanna

sbatch:
  mode: h
  dir: scratch

run:
  filesystem: "/sratch/{os.USER}"
  venvpath: "{os.HOME}/mlcommons-work/python"
  datadir: data
  branch: 'main'

# Submission Information
submission:
  benchmark: multigpu
  submitter: Gregor von Laszewski
  email: laszewski@gmail.com
  org: University of Virginia
  division: closed
  version: multigpu-v1.1
  github_commit_version: TBD
  status: completed
  platform: rivanna
  accelerators_per_node: 1

experiment:
  card_name: "v100,a100"
  gpu_count: "1"
  cpu_num: "1"
  mem: "64GB"
  repeat: "1"
  epoch: "1,10,30,50,100"
  total_epochs: "50,100"
  save_every: "10"

system:
  host: "rivanna"
  num_cpus: 1
  partition: "bii-gpu"
  allocation: bii_dsc_community
  constraint: ""
  reservation: ""
  platform: rivanna
  accelerators_per_node: 1

# Output directory
output_dir: "."
