
name: cloudmask-rivanna

ee:
  time: "6:00:00"
  mode: h
  dir: scratch
  nodes: 1
  ntasks: 2
  mem: 16G

system:
  host: "rivanna"
  python: "3.10.8"
  num_cpus: 1
  platform: rivanna
  accelerators_per_node: 1
  constraint: ""
  reservation: ""

# Submission Information
submission:
  name: cloudmask
  submitter: Gregor von Laszewski
  email: laszewski@gmail.com
  org: University of Virginia
  division: open
  version: mlcommons-osmi-v2.0
  # github_commit_version: TBD
  status: completed
  platform: rivanna
  accelerators_per_node: 1


benchmark:
  name: Osmi
  user: Gregor von Laszewski
  e-mail: laszewski@gmail.com
  organisation: University of Virginia
  division: closed
  status: completed
  platform: rivanna

experiment:
#  card_name: "a100" # "v100,p100"
  card_name: "a100,v100" # "v100,p100"
  # batch: "1,2,4,8,16,32,64,128,256,512,1024"
  batch: "1,2"
  ngpus: "1"
  concurrency: "1"
  model: "small_lstm"
  repeat: "1"

# experiment:
#   server: "localhost"
#   card_name: "a100,v100" # "v100,p100"
  # batch: "1,2,4,8,16,32,64,128,256,512,1024"
#   ngpus: "1"
#   concurrency: "1"
#   #model: "small_lstm"
#   model: "small_lstm,medium_cnn,large_tcnn"
#   repeat: "1,2,3,4,5,6,7,8,9,10"

constant:
  server: "localhost"
  tfs_base_port: 8500
  haproxy_port: 8443
  # config: "config.yaml"
  nrequests: 32768
  algorithm: tfs_grpc_client.py

project:
  user: "/project/bii_dsc_community/{os.USER}"
  dir: "/project/bii_dsc_community/{os.USER}/osmi"

# this is a bug we should be able to use project.dir, it does not show properly in the slurm script
data:
  output: "./outputs"
  sif_dir: "{project.dir}/target/rivanna/image-singularity"
  haproxy_sif: "{data.sif_dir}/haproxy_latest.sif"
  tfs_sif: "{data.sif_dir}/serving_latest-gpu.sif"
  osmi_sif: "{data.sif_dir}/osmi.sif"
  haproxy_cfg_file: haproxy-grpc.cfg

test:
  a: "a"
  b: "{test.a}"

# config:
#   server: "localhost"
#   gpu: "A100" #"V100-SXM2-32GB"
#   batch: [1,2,4,8,16,32,64,128,256,512,1024]
#   nrequests: [32768]
#   ngpus: [1]
#   concurrency: [1,2,4,6,8]
#   ports: [8500]
#   model: ["small_lstm","medium_cnn","large_tcnn"]

user: "{os.USER}"

model_config_list:
  small_lstm:
    base_path: "{project.user}/osmi/models/small_lstm"
    model_platform: "tensorflow"
  medium_cnn:
    base_path: "{project.user}/osmi/models/medium_cnn"
    model_platform: "tensorflow"
  large_tcnn:
    base_path: "{project.user}/osmi/models/large_tcnn"
    model_platform: "tensorflow"

